
# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Scrape website

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # Every two hours.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Run scrapper.
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" colter
